name: conda-dep-check
description: Check conda dependencies
author: dan <dtw545@student.bham.ac.uk>
inputs:
  token:
    description: 'The GitHub token to use for downloading the action, defaults to workflow token'
    required: true
    default: ${{ github.token }}
outputs:
  error:
    description: 'The description of any error that occurred'
    value: ${{ steps.run.outputs.error }}

runs:
  using: 'composite'
  steps:
    - name: Set reusable variables
      shell: bash
      run: |
        echo "ACTION_REPO=conda-dep-check" >> $GITHUB_ENV
        echo "ACTION_ORG=DanW97" >> $GITHUB_ENV
        echo "BINARY_NAME=conda-dep-check" >> $GITHUB_ENV
        echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Add binary extension
      shell: bash
      if: runner.os == 'Windows'
      run: echo "BINARY_NAME=${{ env.BINARY_NAME }}.exe" >> $GITHUB_ENV

    - name: Get Action Version
      id: get_action_version
      shell: bash
      run: |
        echo ${GITHUB_ACTION_PATH}
        finalComponent=$(basename "${GITHUB_ACTION_PATH}")
        echo $finalComponent
        if [[ "$finalComponent" == "$ACTION_REPO" ]]; then
          version=""
        else
          version="$finalComponent"
        fi
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Add action version to env
      shell: bash
      run: |
        echo "PKG_VERSION=${{ steps.get_action_version.outputs.version }}" >> $GITHUB_ENV


    - name: Download Action
      shell: bash
      run: |
        gh release download ${{ steps.get_action_version.outputs.version }} --repo ${{ env.ACTION_ORG }}/${{ env.ACTION_REPO }} --pattern '${{ runner.os }}.tgz'
        tar -xzf ${{ runner.os }}.tgz
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Run Action
      shell: bash
      id: run
      run: ./${{ runner.os }}/${{ env.BINARY_NAME }}
