name: Test consuming this action
on:
  release:
    types: [released]
  workflow_run:
    workflows: ["Release"]
    types: ["completed"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./

