name: Test consuming this action
on:
  release:
    types: [released]
  workflow_run:
    workflows: ["Release"]
    types: ["completed"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./

