name: Test consuming this action
on:
  release:
    types: [released]
  workflow_run:
    workflows: ["Release"]
    types: ["completed"]
jobs:
  test_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./

  test_error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: test
        continue-on-error: true
        uses: ./
