name: Unit tests, linting, and formatting
on: 
  push:
  workflow_dispatch:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Get action version
        id: get_version
        uses: battila7/get-version-action@v2

      # - run: |
      #     echo "PKG_VERSION=${{ steps.get_version.outputs.version-without-v }}" >> $GITHUB_ENV

      - name: Set reusable variables
        shell: bash
        run: |
          echo "ACTION_REPO=conda-dep-check" >> $GITHUB_ENV
          echo "ACTION_ORG=DanW97" >> $GITHUB_ENV
          echo "BINARY_NAME=conda-dep-check" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
      - uses: actions/checkout@v4
      - name: Update Rust
        run: |
          # Act's Ubuntu image
          if ! command -v rustup &> /dev/null
          then
            echo "Installing Rust"
            curl https://sh.rustup.rs -sSf | sh
            source "$HOME/.cargo/env"
          fi
          rustup override set stable
          rustup update stable

      - name: Run tests
        run: cargo test

      - name: Lint
        run: cargo clippy

      - name: Check formatting
        run: cargo fmt --check
